services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Berlin
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - internal

  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - CONFIG_VERSION=generic # Set the desired configuration version here
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - internal
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elmo-router.rule=Host(`env.rz-vm182.gfz.de`) && PathPrefix(`/elmo`)"
      - "traefik.http.routers.elmo-router.entrypoints=https"
      - "traefik.http.routers.elmo-router.middlewares=elmo-stripprefix"
      - "traefik.http.middlewares.elmo-stripprefix.stripprefix.prefixes=/elmo"
      - "traefik.http.services.elmo-service.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"

  web-msl:
    build: .
    ports:
      - "8081:80"
    environment:
      - CONFIG_VERSION=msl # Set the desired configuration version here
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - internal
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elmo-msl-router.rule=Host(`env.rz-vm182.gfz.de`) && PathPrefix(`/elmo-msl`)"
      - "traefik.http.routers.elmo-msl-router.entrypoints=https"
      - "traefik.http.routers.elmo-msl-router.middlewares=elmo-msl-stripprefix"
      - "traefik.http.middlewares.elmo-msl-stripprefix.stripprefix.prefixes=/elmo-msl"
      - "traefik.http.services.elmo-msl-service.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"

  web-gem:
    build: .
    ports:
      - "8082:80"
    environment:
      - CONFIG_VERSION=elmogem # Set the desired configuration version here 
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - internal
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elmo-gem-router.rule=Host(`env.rz-vm182.gfz.de`) && PathPrefix(`/elmo-gem`)"
      - "traefik.http.routers.elmo-gem-router.entrypoints=https"
      - "traefik.http.routers.elmo-gem-router.middlewares=elmo-gem-stripprefix"
      - "traefik.http.middlewares.elmo-gem-stripprefix.stripprefix.prefixes=/elmo-gem"
      - "traefik.http.services.elmo-gem-service.loadbalancer.server.port=80"

volumes:
  db_data:

networks:
  internal:
    driver: bridge
  frontend:
    external:
      name: traefik
