FROM dhi.io/mariadb:11

# Keep MariaDB defaults from the base image.
# Runtime environment variables are injected by docker-compose.
ENV TZ=Europe/Berlin

VOLUME ["/var/lib/mysql"]

ENV MARIADB_PORT=3306
# Overrides the default CMD to explicitly run on port 6770. This part makes the whole Dockerfile elmogem-specific.
CMD ["mariadbd", "--port=${MARIADB_PORT}"]