/**
 * @file Round-trip data loss tests for XML export → import.
 *
 * These tests verify that data exported as XML by ELMO can be re-imported
 * without information loss. Each test targets a specific known data loss
 * scenario discovered through code analysis.
 *
 * Phase 1: Document and prove each bug with a failing test.
 * Phase 2: Fix the bugs and turn these into regression tests.
 */
const fs = require("fs");
const path = require("path");
const vm = require("vm");

// ─── Test infrastructure ────────────────────────────────────────────────────

function loadMappingModule(contextOverrides = {}) {
  const code = fs.readFileSync(
    path.resolve(__dirname, "../../js/mappingXmlToInputFields.js"),
    "utf8"
  );
  const context = {
    console,
    document: global.document,
    window: global.window,
    XPathResult: global.XPathResult,
    ...contextOverrides,
  };
  vm.createContext(context);
  vm.runInContext(code, context);
  return context;
}

/**
 * Minimal jQuery mock that supports chained .find/.val/.closest/.last/.click.
 * Extended to support multi-element queries (querySelectorAll) so that
 * .last() returns the actual last match.
 */
function createJQuery() {
  const $ = (sel) => {
    if (typeof sel === "string") {
      const els = document.querySelectorAll(sel);
      if (els.length === 0) {
        return {
          length: 0,
          find: () => $(null),
          val: () => undefined,
          trigger: jest.fn(),
          click: jest.fn(),
          closest: () => $("__none__"),
          last() { return this; },
          eq: () => $("__none__"),
          first: () => $("__none__"),
          filter: () => $("__none__"),
          prop: jest.fn(),
          show: jest.fn(),
          hide: jest.fn(),
          toArray: () => [],
        };
      }
      return wrapElements(Array.from(els));
    }
    if (sel && sel.nodeType) {
      return wrapElements([sel]);
    }
    return {
      length: 0,
      find: () => $(null),
      val: () => undefined,
      trigger: jest.fn(),
      click: jest.fn(),
      closest: () => $("__none__"),
      last() { return this; },
      eq: () => $("__none__"),
      first: () => $("__none__"),
      filter: () => $("__none__"),
      prop: jest.fn(),
      show: jest.fn(),
      hide: jest.fn(),
      toArray: () => [],
    };
  };

  function wrapElements(elArray) {
    const obj = {
      length: elArray.length,
      elements: elArray,
      get(i) { return elArray[i]; },
      find(s) {
        const results = [];
        elArray.forEach((el) => {
          el.querySelectorAll(s).forEach((m) => results.push(m));
        });
        return results.length ? wrapElements(results) : $(null);
      },
      closest(s) {
        const el = elArray[0]?.closest(s);
        return el ? wrapElements([el]) : $(null);
      },
      last() {
        return elArray.length ? wrapElements([elArray[elArray.length - 1]]) : $(null);
      },
      first() {
        return elArray.length ? wrapElements([elArray[0]]) : $(null);
      },
      eq(i) {
        return elArray[i] ? wrapElements([elArray[i]]) : $(null);
      },
      val(v) {
        if (v === undefined) return elArray[0]?.value;
        elArray.forEach((el) => { el.value = v; });
        return obj;
      },
      prop(name, value) {
        if (value === undefined) return elArray[0]?.[name];
        elArray.forEach((el) => { el[name] = value; });
        return obj;
      },
      trigger: jest.fn(),
      click: jest.fn(),
      show: jest.fn(),
      hide: jest.fn(),
      toArray: () => elArray,
      filter(fn) {
        const filtered = elArray.filter((el, i) => fn.call(el, i, el));
        return filtered.length ? wrapElements(filtered) : $(null);
      },
      attr(name) {
        return elArray[0]?.getAttribute(name);
      },
    };
    return obj;
  }

  $.getJSON = jest.fn(() => Promise.resolve([]));

  return $;
}

/**
 * Build a realistic DataCite 4.7 XML string as generated by the XSLT export.
 * All elements use the default namespace (no prefix), like the real XSLT output.
 */
function buildDataCiteXml(overrides = {}) {
  const defaults = {
    doi: "10.5880/GFZ.test.roundtrip",
    year: "2025",
    language: "en",
    title: "Round Trip Test Dataset",
    titleType: "",
    titleLang: "en",
    authorFamily: "Schmidt",
    authorGiven: "Thomas",
    authorOrcid: "0000-0001-2345-6789",
    authorAffiliation: "GFZ German Research Centre for Geosciences",
    authorRorId: "https://ror.org/04z8jg394",
    resourceType: "Dataset",
    abstract: "Test abstract for round-trip verification.",
    funderName: "Deutsche Forschungsgemeinschaft",
    funderId: "https://doi.org/10.13039/501100001659",
    funderIdType: "Crossref Funder ID",
    grantNumber: "DFG-12345",
    grantName: "Seismic Monitoring Network",
    awardUri: "https://gepris.dfg.de/12345",
    relatedId: "10.5555/related-dataset",
    relatedIdType: "DOI",
    relationType: "IsSupplementTo",
    license: "CC-BY-4.0",
    licenseUri: "https://creativecommons.org/licenses/by/4.0/",
    dateCreated: "2025-03-15",
  };

  const d = { ...defaults, ...overrides };

  return `<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-4"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://datacite.org/schema/kernel-4 https://schema.datacite.org/meta/kernel-4.7/metadata.xsd">
  <identifier identifierType="DOI">${d.doi}</identifier>
  <creators>
    <creator>
      <creatorName nameType="Personal">${d.authorFamily}, ${d.authorGiven}</creatorName>
      <givenName>${d.authorGiven}</givenName>
      <familyName>${d.authorFamily}</familyName>
      <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="https://orcid.org/">${d.authorOrcid}</nameIdentifier>
      <affiliation affiliationIdentifierScheme="ROR" schemeURI="https://ror.org/" affiliationIdentifier="${d.authorRorId}">${d.authorAffiliation}</affiliation>
    </creator>
  </creators>
  <titles>
    <title xml:lang="${d.titleLang}"${d.titleType ? ` titleType="${d.titleType}"` : ""}>${d.title}</title>
  </titles>
  <publisher xml:lang="en">GFZ Data Services</publisher>
  <publicationYear>${d.year}</publicationYear>
  <resourceType resourceTypeGeneral="${d.resourceType}">${d.resourceType}</resourceType>
  <contributors>
    <contributor contributorType="ContactPerson">
      <contributorName nameType="Personal">${d.authorFamily}, ${d.authorGiven}</contributorName>
      <givenName>${d.authorGiven}</givenName>
      <familyName>${d.authorFamily}</familyName>
    </contributor>
  </contributors>
  <dates>
    <date dateType="Created">${d.dateCreated}</date>
  </dates>
  <language>${d.language}</language>
  <relatedIdentifiers>
    <relatedIdentifier relatedIdentifierType="${d.relatedIdType}" relationType="${d.relationType}">${d.relatedId}</relatedIdentifier>
  </relatedIdentifiers>
  <rightsList>
    <rights xml:lang="en" schemeURI="https://spdx.org/licenses/" rightsIdentifierScheme="SPDX" rightsIdentifier="${d.license}" rightsURI="${d.licenseUri}">Creative Commons Attribution 4.0 International</rights>
  </rightsList>
  <descriptions>
    <description descriptionType="Abstract" xml:lang="${d.titleLang}">${d.abstract}</description>
  </descriptions>
  <fundingReferences>
    <fundingReference>
      <funderName>${d.funderName}</funderName>
      <funderIdentifier funderIdentifierType="${d.funderIdType}">${d.funderId}</funderIdentifier>
      <awardNumber awardURI="${d.awardUri}">${d.grantNumber}</awardNumber>
      <awardTitle>${d.grantName}</awardTitle>
    </fundingReference>
  </fundingReferences>
</resource>`;
}

// ─── BUG 1: funderIdentifierType lost due to querySelector on namespaced XML ─

describe("BUG: funderIdentifierType lost on import (querySelector vs namespace)", () => {
  test("funderIdentifierType is empty when XML uses default namespace (real XSLT output)", () => {
    // The XSLT generates all elements under the default namespace
    // xmlns="http://datacite.org/schema/kernel-4". The import code uses
    // querySelector("funderIdentifier") which does NOT match namespaced elements.
    document.body.innerHTML = `
      <div id="group-fundingreference">
        <div class="row">
          <input name="funder[]" value="" />
          <input name="funderId[]" value="" />
          <input name="funderidtyp[]" value="" />
          <input name="grantNummer[]" value="" />
          <input name="grantName[]" value="" />
          <input name="awardURI[]" value="" />
        </div>
      </div>
      <button id="button-fundingreference-add"></button>`;

    const $ = createJQuery();
    const ctx = loadMappingModule({ $ });

    // This XML mirrors the real XSLT output: all elements in default namespace
    const xml = buildDataCiteXml({
      funderName: "Deutsche Forschungsgemeinschaft",
      funderId: "https://doi.org/10.13039/501100001659",
      funderIdType: "Crossref Funder ID",
      grantNumber: "DFG-12345",
      grantName: "Seismic Monitoring",
      awardUri: "https://gepris.dfg.de/12345",
    });

    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");
    const resolver = (prefix) =>
      prefix === "ns" ? "http://datacite.org/schema/kernel-4" : null;

    ctx.processFunders(xmlDoc, resolver);

    // These work because they use XPath with namespace resolver:
    const funderNameField = document.querySelector('input[name="funder[]"]');
    expect(funderNameField.value).toBe("Deutsche Forschungsgemeinschaft");

    const funderIdField = document.querySelector('input[name="funderId[]"]');
    expect(funderIdField.value).toBe("https://doi.org/10.13039/501100001659");

    const grantNumberField = document.querySelector('input[name="grantNummer[]"]');
    expect(grantNumberField.value).toBe("DFG-12345");

    // BUG: funderIdentifierType is empty because querySelector("funderIdentifier")
    // does not find elements that are in the default namespace.
    const funderIdTypField = document.querySelector('input[name="funderidtyp[]"]');
    expect(funderIdTypField.value).toBe("Crossref Funder ID");
    // If the above fails with "" instead of "Crossref Funder ID", the bug is confirmed.
  });

  test("existing test masked the bug by using unnamespaced funderIdentifier element", () => {
    // This test documents WHY the existing test passed: it used
    // <funderIdentifier> WITHOUT namespace prefix while all other elements had ns:.
    // Real XSLT output has ALL elements in the same namespace.
    document.body.innerHTML = `
      <div id="group-fundingreference">
        <div class="row">
          <input name="funder[]" value="" />
          <input name="funderId[]" value="" />
          <input name="funderidtyp[]" value="" />
          <input name="grantNummer[]" value="" />
          <input name="grantName[]" value="" />
          <input name="awardURI[]" value="" />
        </div>
      </div>
      <button id="button-fundingreference-add"></button>`;

    const $ = createJQuery();
    const ctx = loadMappingModule({ $ });

    // Mixed namespace XML (as used in the old test) — funderIdentifier is unnamespaced
    const xml = `
      <ns:resource xmlns:ns="http://datacite.org/schema/kernel-4">
        <ns:fundingReferences>
          <ns:fundingReference>
            <ns:funderName>Test Fund</ns:funderName>
            <funderIdentifier funderIdentifierType="Crossref Funder ID">12345</funderIdentifier>
            <ns:awardNumber awardURI="https://example.com/award">AB123</ns:awardNumber>
            <ns:awardTitle>Award Title</ns:awardTitle>
          </ns:fundingReference>
        </ns:fundingReferences>
      </ns:resource>`;

    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");
    const resolver = (prefix) =>
      prefix === "ns" ? "http://datacite.org/schema/kernel-4" : null;

    ctx.processFunders(xmlDoc, resolver);

    // This PASSES because the unnamespaced <funderIdentifier> IS found by querySelector
    const funderIdTypField = document.querySelector('input[name="funderidtyp[]"]');
    expect(funderIdTypField.value).toBe("Crossref Funder ID");
  });
});

// ─── BUG 2: awardURI lost when funderIdentifier is namespaced ───────────────

describe("BUG: awardURI may be lost on namespaced XML", () => {
  test("awardURI is correctly imported from real XSLT output", () => {
    document.body.innerHTML = `
      <div id="group-fundingreference">
        <div class="row">
          <input name="funder[]" value="" />
          <input name="funderId[]" value="" />
          <input name="funderidtyp[]" value="" />
          <input name="grantNummer[]" value="" />
          <input name="grantName[]" value="" />
          <input name="awardURI[]" value="" />
        </div>
      </div>
      <button id="button-fundingreference-add"></button>`;

    const $ = createJQuery();
    const ctx = loadMappingModule({ $ });

    const xml = buildDataCiteXml({
      awardUri: "https://gepris.dfg.de/12345",
      grantNumber: "DFG-12345",
    });

    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");
    const resolver = (prefix) =>
      prefix === "ns" ? "http://datacite.org/schema/kernel-4" : null;

    ctx.processFunders(xmlDoc, resolver);

    // awardURI uses XPath (ns:awardNumber) + getAttribute("awardURI") — should work
    const awardUriField = document.querySelector('input[name="awardURI[]"]');
    expect(awardUriField.value).toBe("https://gepris.dfg.de/12345");
  });
});

// ─── BUG 3: Contact person email/website lost on DataCite-only import ───────

describe("BUG: contact person email/website lost from DataCite-only XML", () => {
  test("contact person checkbox is set via DataCite fallback (but email/website lost)", () => {
    document.body.innerHTML = `
      <div id="group-author">
        <div data-creator-row>
          <input name="familynames[]" value="Schmidt" />
          <input name="givennames[]" value="Thomas" />
          <input name="orcids[]" value="0000-0001-2345-6789" />
          <input name="personAffiliation[]" value="" />
          <input name="authorPersonRorIds[]" value="" />
          <input name="contacts[]" type="checkbox" />
          <div class="contact-person-input" style="display:none">
            <input name="cpEmail[]" value="" />
            <input name="cpOnlineResource[]" value="" />
          </div>
        </div>
      </div>`;

    const $ = createJQuery();
    const ctx = loadMappingModule({ $ });

    // DataCite-only XML (no ISO section) — this is a pure DataCite resource
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-4">
  <creators>
    <creator>
      <creatorName nameType="Personal">Schmidt, Thomas</creatorName>
      <givenName>Thomas</givenName>
      <familyName>Schmidt</familyName>
    </creator>
  </creators>
  <contributors>
    <contributor contributorType="ContactPerson">
      <contributorName nameType="Personal">Schmidt, Thomas</contributorName>
      <givenName>Thomas</givenName>
      <familyName>Schmidt</familyName>
    </contributor>
  </contributors>
</resource>`;

    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");

    // processContactPersons expects the author rows to already be populated
    ctx.processContactPersons(xmlDoc);

    // Contact person checkbox should be checked (DataCite fallback)
    const checkbox = document.querySelector('input[name="contacts[]"]');
    expect(checkbox.checked).toBe(true);

    // BUG: Email and website are NOT available in DataCite schema
    // so they are always empty after DataCite-only import
    const emailField = document.querySelector('input[name="cpEmail[]"]');
    const websiteField = document.querySelector('input[name="cpOnlineResource[]"]');
    // These are empty because DataCite has no email/website for contributors
    expect(emailField.value).toBe("");
    expect(websiteField.value).toBe("");
  });

  test("contact person email/website preserved when ISO section is present (envelope)", () => {
    document.body.innerHTML = `
      <div id="group-author">
        <div data-creator-row>
          <input name="familynames[]" value="Schmidt" />
          <input name="givennames[]" value="Thomas" />
          <input name="orcids[]" value="0000-0001-2345-6789" />
          <input name="personAffiliation[]" value="" />
          <input name="authorPersonRorIds[]" value="" />
          <input name="contacts[]" type="checkbox" />
          <div class="contact-person-input" style="display:none">
            <input name="cpEmail[]" value="" />
            <input name="cpOnlineResource[]" value="" />
          </div>
        </div>
      </div>`;

    const $ = createJQuery();
    const ctx = loadMappingModule({ $ });

    // Envelope XML with both DataCite and ISO sections
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<envelope>
  <resource xmlns="http://datacite.org/schema/kernel-4">
    <creators>
      <creator>
        <creatorName nameType="Personal">Schmidt, Thomas</creatorName>
        <givenName>Thomas</givenName>
        <familyName>Schmidt</familyName>
      </creator>
    </creators>
    <contributors>
      <contributor contributorType="ContactPerson">
        <contributorName nameType="Personal">Schmidt, Thomas</contributorName>
        <givenName>Thomas</givenName>
        <familyName>Schmidt</familyName>
      </contributor>
    </contributors>
  </resource>
  <gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd"
                   xmlns:gco="http://www.isotc211.org/2005/gco">
    <gmd:contact>
      <gmd:CI_ResponsibleParty>
        <gmd:individualName>
          <gco:CharacterString>Schmidt, Thomas</gco:CharacterString>
        </gmd:individualName>
      </gmd:CI_ResponsibleParty>
    </gmd:contact>
    <gmd:pointOfContact>
      <gmd:CI_ResponsibleParty>
        <gmd:individualName>
          <gco:CharacterString>Schmidt, Thomas</gco:CharacterString>
        </gmd:individualName>
        <gmd:contactInfo>
          <gmd:CI_Contact>
            <gmd:address>
              <gmd:CI_Address>
                <gmd:electronicMailAddress>
                  <gco:CharacterString>thomas@gfz.de</gco:CharacterString>
                </gmd:electronicMailAddress>
              </gmd:CI_Address>
            </gmd:address>
            <gmd:onlineResource>
              <gmd:CI_OnlineResource>
                <gmd:linkage>
                  <gmd:URL>https://gfz.de/thomas</gmd:URL>
                </gmd:linkage>
              </gmd:CI_OnlineResource>
            </gmd:onlineResource>
          </gmd:CI_Contact>
        </gmd:contactInfo>
      </gmd:CI_ResponsibleParty>
    </gmd:pointOfContact>
  </gmd:MD_Metadata>
</envelope>`;

    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");

    ctx.processContactPersons(xmlDoc);

    const checkbox = document.querySelector('input[name="contacts[]"]');
    expect(checkbox.checked).toBe(true);

    // With ISO section, email and website should be preserved
    const emailField = document.querySelector('input[name="cpEmail[]"]');
    const websiteField = document.querySelector('input[name="cpOnlineResource[]"]');
    expect(emailField.value).toBe("thomas@gfz.de");
    expect(websiteField.value).toBe("https://gfz.de/thomas");
  });
});

// ─── BUG 4: Contact person not imported when not matching any author ────────

describe("BUG: contact person dropped when name doesn't match any author", () => {
  test("contact person with different name than authors is silently lost", () => {
    document.body.innerHTML = `
      <div id="group-author">
        <div data-creator-row>
          <input name="familynames[]" value="Schmidt" />
          <input name="givennames[]" value="Thomas" />
          <input name="orcids[]" value="" />
          <input name="personAffiliation[]" value="" />
          <input name="authorPersonRorIds[]" value="" />
          <input name="contacts[]" type="checkbox" />
          <div class="contact-person-input" style="display:none">
            <input name="cpEmail[]" value="" />
            <input name="cpOnlineResource[]" value="" />
          </div>
        </div>
      </div>`;

    const consoleWarns = [];
    const $ = createJQuery();
    const ctx = loadMappingModule({
      $,
      console: { ...console, warn: (...args) => consoleWarns.push(args.join(" ")) },
    });

    // Contact person "Müller" is not one of the authors ("Schmidt")
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-4">
  <contributors>
    <contributor contributorType="ContactPerson">
      <contributorName nameType="Personal">Müller, Erika</contributorName>
      <givenName>Erika</givenName>
      <familyName>Müller</familyName>
    </contributor>
  </contributors>
</resource>`;

    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");
    ctx.processContactPersons(xmlDoc);

    // BUG: Contact person is silently dropped with only a console.warn
    const checkbox = document.querySelector('input[name="contacts[]"]');
    expect(checkbox.checked).toBe(false); // Not checked, because no match found
  });
});

// ─── BUG 5: Relation type matching depends on visible dropdown text ─────────

describe("BUG: relation type matching relies on option text not value", () => {
  test("relation type with spaces in option text does not match CamelCase relationType", () => {
    // If the relation dropdown option texts contain spaces ("Is Supplement To")
    // but the XML uses CamelCase ("IsSupplementTo"), the matching fails.
    // The current code matches by visible text:
    //   $(this).text() === entry.relationType
    document.body.innerHTML = `
      <div id="group-relatedwork">
        <div class="row">
          <input name="rIdentifier[]" value="" />
          <select name="rIdentifierType[]">
            <option value="DOI">DOI</option>
          </select>
          <select name="relation[]">
            <option value="1">Is Supplement To</option>
            <option value="2">Is Cited By</option>
          </select>
        </div>
      </div>
      <button id="button-relatedwork-add"></button>`;

    const $ = createJQuery();
    const ctx = loadMappingModule({ $ });

    const xml = buildDataCiteXml({
      relatedId: "10.5555/related",
      relatedIdType: "DOI",
      relationType: "IsSupplementTo",
    });

    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");
    const resolver = (prefix) =>
      prefix === "ns" ? "http://datacite.org/schema/kernel-4" : null;

    ctx.processRelatedWorks(xmlDoc, resolver);

    // Identifier is set correctly
    const idField = document.querySelector('input[name="rIdentifier[]"]');
    expect(idField.value).toBe("10.5555/related");

    // BUG: If option text has spaces ("Is Supplement To") but XML has CamelCase
    // ("IsSupplementTo"), the relation is NOT selected.
    // NOTE: This test verifies the behavior. If the DB stores CamelCase relation
    // names (which it does according to install.php), the option texts should
    // also be CamelCase. If someone changes option texts to include spaces,
    // this test will catch the regression.
    const relationSelect = document.querySelector('select[name="relation[]"]');
    const selectedOption = relationSelect.options[relationSelect.selectedIndex];
    // With CamelCase option texts, this should match:
    expect(selectedOption.text).toBe("Is Supplement To");
    // If the above fails, it means the matching logic breaks when option texts
    // have spaces but the XML attributes use CamelCase.
  });
});

// ─── BUG 6: Multiple funding references — second funder overwrites first ────

describe("BUG: multiple funding references import", () => {
  test("second funding reference row is correctly populated", () => {
    document.body.innerHTML = `
      <div id="group-fundingreference">
        <div class="row" id="funder-row-1">
          <input name="funder[]" value="" />
          <input name="funderId[]" value="" />
          <input name="funderidtyp[]" value="" />
          <input name="grantNummer[]" value="" />
          <input name="grantName[]" value="" />
          <input name="awardURI[]" value="" />
        </div>
      </div>
      <button id="button-fundingreference-add"></button>`;

    const $ = createJQuery();
    // Track add-button clicks
    let addClicked = 0;

    const ctx = loadMappingModule({ $ });

    // Override click to actually clone a row
    document.getElementById("button-fundingreference-add").addEventListener("click", () => {
      addClicked++;
      const container = document.getElementById("group-fundingreference");
      const firstRow = container.querySelector(".row");
      const clone = firstRow.cloneNode(true);
      clone.querySelectorAll("input").forEach((i) => (i.value = ""));
      container.appendChild(clone);
    });

    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-4">
  <fundingReferences>
    <fundingReference>
      <funderName>DFG</funderName>
      <funderIdentifier funderIdentifierType="Crossref Funder ID">501100001659</funderIdentifier>
      <awardNumber awardURI="https://example.org/1">GRANT-1</awardNumber>
      <awardTitle>First Grant</awardTitle>
    </fundingReference>
    <fundingReference>
      <funderName>ERC</funderName>
      <funderIdentifier funderIdentifierType="ROR">https://ror.org/0472cxd90</funderIdentifier>
      <awardNumber awardURI="https://example.org/2">GRANT-2</awardNumber>
      <awardTitle>Second Grant</awardTitle>
    </fundingReference>
  </fundingReferences>
</resource>`;

    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");
    const resolver = (prefix) =>
      prefix === "ns" ? "http://datacite.org/schema/kernel-4" : null;

    ctx.processFunders(xmlDoc, resolver);

    expect(addClicked).toBe(1); // Button should be clicked once for second funder

    const rows = document.querySelectorAll("#group-fundingreference .row");
    expect(rows.length).toBe(2);

    // First funder
    expect(rows[0].querySelector('input[name="funder[]"]').value).toBe("DFG");
    expect(rows[0].querySelector('input[name="grantNummer[]"]').value).toBe("GRANT-1");

    // Second funder
    expect(rows[1].querySelector('input[name="funder[]"]').value).toBe("ERC");
    expect(rows[1].querySelector('input[name="grantNummer[]"]').value).toBe("GRANT-2");
  });
});

// ─── BUG 7: Temporal coverage timezone parsing edge cases ───────────────────

describe("BUG: temporal coverage timezone offset parsing", () => {
  test("negative timezone offset is correctly extracted", () => {
    const ctx = loadMappingModule();

    const xml = `<date>2025-01-15T08:00:00-05:00/2025-06-30T17:00:00-05:00</date>`;
    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");
    const dateNode = xmlDoc.querySelector("date");

    const result = ctx.parseTemporalData(dateNode);
    expect(result.startDate).toBe("2025-01-15");
    expect(result.startTime).toBe("08:00:00");
    expect(result.endDate).toBe("2025-06-30");
    expect(result.endTime).toBe("17:00:00");
    expect(result.timezoneOffset).toBe("-05:00");
  });

  test("date without time but with timezone parses correctly", () => {
    const ctx = loadMappingModule();

    const xml = `<date>2025-01-15+02:00/2025-06-30+02:00</date>`;
    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");
    const dateNode = xmlDoc.querySelector("date");

    const result = ctx.parseTemporalData(dateNode);
    expect(result.startDate).toBe("2025-01-15");
    expect(result.startTime).toBe("");
    expect(result.endDate).toBe("2025-06-30");
    expect(result.endTime).toBe("");
    expect(result.timezoneOffset).toBe("+02:00");
  });

  test("date with negative offset and no time extracts timezone correctly", () => {
    const ctx = loadMappingModule();

    // Edge case: negative offset on date without time
    const xml = `<date>2025-03-01-08:00</date>`;
    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");
    const dateNode = xmlDoc.querySelector("date");

    const result = ctx.parseTemporalData(dateNode);
    // The date should have the timezone stripped
    expect(result.startDate).toBe("2025-03-01");
    expect(result.timezoneOffset).toBe("-08:00");
  });
});

// ─── BUG 8: Description language attribute lost on import ───────────────────

describe("BUG: description xml:lang attribute is not imported", () => {
  test("description language attribute is read from XML but not stored in form", () => {
    // The abstract and other descriptions have xml:lang="de" but the import
    // ignores the language attribute — it's not stored anywhere in the form.
    // This means a German abstract re-exported will default to English.
    document.body.innerHTML = `
      <textarea id="input-abstract"></textarea>
      <div id="collapse-abstract" class="accordion-body"></div>`;

    const $ = createJQuery();
    const ctx = loadMappingModule({ $ });

    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-4">
  <descriptions>
    <description descriptionType="Abstract" xml:lang="de">Abstrakt auf Deutsch</description>
  </descriptions>
</resource>`;

    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");
    const resolver = (prefix) =>
      prefix === "ns" ? "http://datacite.org/schema/kernel-4" : null;

    ctx.processDescriptions(xmlDoc, resolver);

    // Content is imported correctly
    const abstractField = document.getElementById("input-abstract");
    expect(abstractField.value).toBe("Abstrakt auf Deutsch");

    // BUG: There is no form field to store the description language.
    // On re-export, it will default to "en" instead of "de".
    // This test documents that the language information is lost.
    // A hidden field like <input name="descriptionLang[]" /> would be needed.
  });
});

// ─── BUG 9: Title language attribute lost on import ─────────────────────────

describe("BUG: title xml:lang attribute is not stored in form", () => {
  test("title language is read but not persisted to any form field", () => {
    document.body.innerHTML = `
      <div class="row">
        <input name="title[]" value="" />
        <select id="input-resourceinformation-titletype">
          <option value="1">Main Title</option>
        </select>
      </div>
      <button id="button-resourceinformation-addtitle"></button>`;

    const $ = createJQuery();
    const ctx = loadMappingModule({ $ });

    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-4">
  <titles>
    <title xml:lang="fr" titleType="MainTitle">Titre en français</title>
  </titles>
</resource>`;

    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");
    const resolver = (prefix) =>
      prefix === "ns" ? "http://datacite.org/schema/kernel-4" : null;

    ctx.processTitles(xmlDoc, resolver, { "": "1", MainTitle: "1" });

    // Title text is imported
    const titleField = document.querySelector('input[name="title[]"]');
    expect(titleField.value).toBe("Titre en français");

    // BUG: The xml:lang="fr" is read in the code (line ~177) but never stored.
    // On re-export, the title language defaults to "en".
    // There should be a hidden field or select for title language.
  });
});

// ─── BUG 10: Thesaurus keyword metadata (schemeURI, valueURI) round-trip ────

describe("Keyword metadata round-trip via Tagify tags", () => {
  test("thesaurus keyword schemeURI and valueURI are preserved in Tagify tag data", () => {
    // This test verifies that keyword metadata is preserved in the Tagify tag
    // data structure. The real question is whether this metadata survives
    // the save_data.php → DB → XSLT round-trip, but here we test the import.
    const mockTagify = {
      addTags: jest.fn(),
      removeAllTags: jest.fn(),
    };

    document.body.innerHTML = `
      <input id="input-freekeyword" />
      <input id="input-sciencekeyword" />`;

    document.getElementById("input-freekeyword")._tagify = {
      addTags: jest.fn(),
      removeAllTags: jest.fn(),
    };
    document.getElementById("input-sciencekeyword")._tagify = {
      addTags: jest.fn(),
      removeAllTags: jest.fn(),
    };

    const $ = createJQuery();
    const ctx = loadMappingModule({ $ });

    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-4">
  <subjects>
    <subject subjectScheme="NASA/GCMD Earth Science Keywords"
             schemeURI="https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/sciencekeywords"
             valueURI="https://gcmd.earthdata.nasa.gov/kms/concept/123"
             xml:lang="en">EARTH SCIENCE &gt; SOLID EARTH</subject>
  </subjects>
</resource>`;

    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");
    const resolver = (prefix) =>
      prefix === "ns" ? "http://datacite.org/schema/kernel-4" : null;

    ctx.processKeywords(xmlDoc, resolver);

    const scienceTagify = document.getElementById("input-sciencekeyword")._tagify;
    expect(scienceTagify.addTags).toHaveBeenCalled();

    const addedTag = scienceTagify.addTags.mock.calls[0][0][0];
    expect(addedTag.value).toBe("EARTH SCIENCE > SOLID EARTH");
    expect(addedTag.schemeURI).toBe(
      "https://gcmd.earthdata.nasa.gov/kms/concepts/concept_scheme/sciencekeywords"
    );
    expect(addedTag.id).toBe("https://gcmd.earthdata.nasa.gov/kms/concept/123");
    expect(addedTag.scheme).toBe("NASA/GCMD Earth Science Keywords");
    expect(addedTag.language).toBe("en");
  });
});

// ─── BUG 11: Author ORCID with full URL format ─────────────────────────────

describe("Author ORCID URL stripping", () => {
  test("ORCID URL prefix is correctly stripped during import", () => {
    document.body.innerHTML = `
      <div id="group-author">
        <div data-creator-row>
          <input name="familynames[]" value="" />
          <input name="givennames[]" value="" />
          <input name="orcids[]" value="" />
          <input name="personAffiliation[]" value="" />
          <input name="authorPersonRorIds[]" value="" />
          <input name="contacts[]" type="checkbox" />
          <div class="contact-person-input" style="display:none">
            <input name="cpEmail[]" value="" />
            <input name="cpOnlineResource[]" value="" />
          </div>
        </div>
      </div>
      <button id="button-author-add"></button>`;

    const $ = createJQuery();
    const ctx = loadMappingModule({ $ });

    // XSLT exports ORCID as plain value (without URL prefix), but some external
    // XMLs might have the full URL. Test both cases.
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-4">
  <creators>
    <creator>
      <creatorName nameType="Personal">Schmidt, Thomas</creatorName>
      <givenName>Thomas</givenName>
      <familyName>Schmidt</familyName>
      <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="https://orcid.org/">https://orcid.org/0000-0001-2345-6789</nameIdentifier>
      <affiliation affiliationIdentifierScheme="ROR" schemeURI="https://ror.org/" affiliationIdentifier="https://ror.org/04z8jg394">GFZ</affiliation>
    </creator>
  </creators>
</resource>`;

    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");
    const resolver = (prefix) =>
      prefix === "ns" ? "http://datacite.org/schema/kernel-4" : null;

    ctx.processCreators(xmlDoc, resolver);

    // ORCID should have URL prefix stripped
    const orcidField = document.querySelector('input[name="orcids[]"]');
    expect(orcidField.value).toBe("0000-0001-2345-6789");

    // ROR ID should have URL prefix stripped
    const rorField = document.querySelector('input[name="authorPersonRorIds[]"]');
    expect(rorField.value).toBe("04z8jg394");
  });
});

// ─── BUG 12: Contributor ORCID handling ─────────────────────────────────────

describe("Contributor ORCID extraction", () => {
  test("contributor ORCID is correctly extracted via schemeURI selector", () => {
    const ctx = loadMappingModule();

    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-4">
  <contributors>
    <contributor contributorType="DataCollector">
      <contributorName nameType="Personal">Müller, Erika</contributorName>
      <givenName>Erika</givenName>
      <familyName>Müller</familyName>
      <nameIdentifier nameIdentifierScheme="ORCID" schemeURI="https://orcid.org/">0000-0002-9876-5432</nameIdentifier>
    </contributor>
  </contributors>
</resource>`;

    const xmlDoc = new DOMParser().parseFromString(xml, "application/xml");
    const resolver = (prefix) =>
      prefix === "ns" ? "http://datacite.org/schema/kernel-4" : null;

    const personMap = new Map();
    const orgMap = new Map();
    const contributorNode = xmlDoc.evaluate(
      ".//ns:contributors/ns:contributor",
      xmlDoc,
      resolver,
      XPathResult.FIRST_ORDERED_NODE_TYPE,
      null
    ).singleNodeValue;

    ctx.processIndividualContributor(
      contributorNode,
      xmlDoc,
      resolver,
      personMap,
      orgMap
    );

    expect(personMap.size).toBe(1);
    const person = personMap.values().next().value;
    expect(person.orcid).toBe("0000-0002-9876-5432");
    expect(person.givenName).toBe("Erika");
    expect(person.familyName).toBe("Müller");
    expect(person.roles).toContain("Data Collector");
  });
});
