import { test, expect } from '@playwright/test';
import { navigateToHome, expectNavbarVisible } from '../../utils';

/**
 * ELMO-GEM Feature Toggle Verification
 *
 * Confirms that when showGGMsProperties=true in settings.php,
 * the following features are correctly hidden:
 * - GEMET thesaurus
 * - Chronostratigraphy (ICS) thesaurus
 * - Used Instruments form group
 *
 * This is a regression test for the feature override system that applies
 * these restrictions to the ELMO-GEM variant.
 */
test.describe('ELMO-GEM Feature Toggle Override', () => {
  test.beforeEach(async ({ page }) => {
    await navigateToHome(page);
    await expectNavbarVisible(page);
  });

  test('does NOT render GEMET and Chronostratigraphy thesauri', async ({ page }) => {
    // Thesaurus input items are dynamically generated by js/thesauri.js
    const thesaurusItems = page.locator('.thesaurus-input-item');
    const itemCount = await thesaurusItems.count();

    // Should have exactly 3 thesauri: science_keywords, platforms, instruments
    // GEMET and chronostratigraphy should be filtered out by hiddenThesauri override
    expect(itemCount).toBe(3);

    // Verify the expected thesauri are present
    const expectedThesauri = [
      'GCMD Science Keywords',
      'GCMD Platforms',
      'GCMD Instruments',
    ];

    for (const name of expectedThesauri) {
      const label = page.locator(`.thesaurus-input-item:has(.thesaurus-input-label:has-text("${name}"))`);
      await expect(label).toBeVisible();
    }

    // Verify GEMET is NOT present
    const gemetLabel = page.locator('.thesaurus-input-label:has-text("GEMET")');
    await expect(gemetLabel).toHaveCount(0);

    // Verify Chronostratigraphy (ICS) is NOT present
    const chronolabel = page.locator('.thesaurus-input-label:has-text("ICS Chronostratigraphy")');
    await expect(chronolabel).toHaveCount(0);
  });

  test('does NOT render Used Instruments form group', async ({ page }) => {
    // Used Instruments form group should not be in the DOM when showUsedInstruments=false
    // (which is forced by the override when showGGMsProperties=true)
    const usedInstrumentsGroup = page.locator('#group-usedinstruments');
    await expect(usedInstrumentsGroup).toHaveCount(0);

    // Verify the form group container doesn't exist
    const usedInstrumentsContainer = page.locator('[id*="usedinstruments"]');
    const count = await usedInstrumentsContainer.count();
    expect(count).toBe(0);
  });

  test('window.ELMO_FEATURES.hiddenThesauri contains the expected values', async ({ page }) => {
    // Verify that JavaScript has access to the hidden thesauri list
    const hiddenThesauri = await page.evaluate(() => {
      return (window as any).ELMO_FEATURES?.hiddenThesauri || [];
    });

    // Should contain exactly chronostratigraphy and gemet
    expect(hiddenThesauri).toContain('chronostratigraphy');
    expect(hiddenThesauri).toContain('gemet');
    expect(hiddenThesauri.length).toBe(2);
  });
});
