import { readFileSync, writeFileSync } from 'fs';
import path from 'path';

export type Variant = 'generic' | 'gem' | 'msl' | 'igsn';

interface VariantConfig {
  // MSL master switch (derived MSL flags are synced in the lock file)
  showMslMode: boolean;
  // GEM-specific
  showGGMsProperties: boolean;
  // Shared form groups (IGSN turns several off)
  showUsedInstruments: boolean;
  showSpatialTemporalCoverage: boolean;
  showFreeKeywords: boolean;
  showRelatedWork: boolean;
  showThesauri: boolean;
}

/**
 * Per-variant settings that are written into settings.php before each test run.
 * Values mirror the environment variables used by the CI multi-server setup.
 */
const VARIANT_SETTINGS: Record<Variant, VariantConfig> = {
  generic: {
    showMslMode: false,
    showGGMsProperties: false,
    showUsedInstruments: true,
    showSpatialTemporalCoverage: true,
    showFreeKeywords: true,
    showRelatedWork: true,
    showThesauri: true,
  },
  gem: {
    showMslMode: false,
    showGGMsProperties: true,
    showUsedInstruments: false,
    showSpatialTemporalCoverage: false,
    showFreeKeywords: true,
    showRelatedWork: true,
    showThesauri: true,
  },
  msl: {
    showMslMode: true,
    showGGMsProperties: false,
    showUsedInstruments: false,
    showSpatialTemporalCoverage: true,
    showFreeKeywords: true,
    showRelatedWork: true,
    showThesauri: true,
  },
  igsn: {
    showMslMode: false,
    showGGMsProperties: false,
    showUsedInstruments: true,
    showSpatialTemporalCoverage: true,
    showFreeKeywords: true,
    showRelatedWork: true,
    showThesauri: true,
  },
};

/** Path to settings.php, resolved from the project root via process.cwd(). */
const SETTINGS_PHP = path.join(process.cwd(), 'settings.php');
/** Lock file applied after env overrides in settings.php / settings.elmo.php. */
const VARIANT_LOCK_PHP = path.join(process.cwd(), 'playwright-variant-lock.php');

const MSL_DERIVED_FLAGS = [
  'showMslLabs',
  'showMslVocabs',
  'showMslDefaultFreeKeywords',
  'showMslLogo',
] as const;

const VARIANT_LOCK_FLAGS: Array<keyof VariantConfig> = [
  'showGGMsProperties',
  'showUsedInstruments',
  'showSpatialTemporalCoverage',
  'showFreeKeywords',
  'showRelatedWork',
  'showThesauri',
];

/**
 * Replaces `$varName = true/false;` assignments in settings.php.
 * Only touches plain boolean default assignments; filter_var() lines are
 * intentionally left untouched so env-var overrides still work in CI.
 */
function setBoolVar(content: string, varName: string, value: boolean): string {
  const phpVal = value ? 'true' : 'false';
  return content.replace(
    new RegExp(`(\\$${varName}\\s*=\\s*)(true|false)(;)`, 'g'),
    `$1${phpVal}$3`,
  );
}

function writeVariantLockFile(variant: Variant): void {
  const config = VARIANT_SETTINGS[variant];
  const lines = [
    '<?php',
    '// Auto-generated by Playwright variant setup. Do not edit manually.',
    `$showMslMode = ${config.showMslMode ? 'true' : 'false'};`,
  ];

  for (const flag of MSL_DERIVED_FLAGS) {
    lines.push(`$${flag} = $showMslMode;`);
  }

  for (const flag of VARIANT_LOCK_FLAGS) {
    lines.push(`$${flag} = ${config[flag] ? 'true' : 'false'};`);
  }

  writeFileSync(VARIANT_LOCK_PHP, `${lines.join('\n')}\n`, 'utf-8');
}

/**
 * Applies the settings for the given variant to settings.php.
 * PHP re-reads the file on every request so no server restart is needed.
 *
 * We patch plain boolean assignments in settings.php and also write
 * playwright-variant-lock.php, which settings.php includes after any
 * environment-variable overrides. That keeps Docker env vars such as
 * SHOW_GGMS_PROPERTIES or SHOW_MSL_MODE from defeating the active variant.
 */
export function applyVariantSettings(variant: Variant): void {
  let content = readFileSync(SETTINGS_PHP, 'utf-8');

  content = setBoolVar(content, 'showMslMode', VARIANT_SETTINGS[variant].showMslMode);

  for (const [varName, value] of Object.entries(VARIANT_SETTINGS[variant])) {
    content = setBoolVar(content, varName, value);
  }

  for (const flag of MSL_DERIVED_FLAGS) {
    content = setBoolVar(content, flag, VARIANT_SETTINGS[variant].showMslMode);
  }

  writeFileSync(SETTINGS_PHP, content, 'utf-8');
  writeVariantLockFile(variant);
  console.log(`\n[variant-setup] Applied ${variant.toUpperCase()} settings to settings.php`);
}
