name: PHP 8.2 Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: mde2-msl-test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql, mysqli, zip
        coverage: xdebug

    - name: Install PHP dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest
        composer dump-autoload -o

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install JS dependencies
      run: |
        npm install

    - name: Wait for MySQL to be ready
      run: |
        for i in {30..0}; do
          if mysqladmin ping -h127.0.0.1 --silent; then
            break
          fi
          echo 'Waiting for MySQL...'
          sleep 5
        done
        if [ "$i" = 0 ]; then
          echo >&2 'MySQL did not start in time.'
          exit 1
        fi

    - name: Grant privileges to test_user
      run: |
        mysql -h127.0.0.1 -uroot -proot_password -e "
          CREATE USER IF NOT EXISTS 'test_user'@'%' IDENTIFIED BY 'test_password';
          GRANT ALL PRIVILEGES ON *.* TO 'test_user'@'%';
          FLUSH PRIVILEGES;
        "

    - name: Set test environment variables
      run: |
        # Override just the database settings for testing
        echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
        echo "DB_USER=test_user" >> $GITHUB_ENV
        echo "DB_PASSWORD=test_password" >> $GITHUB_ENV
        echo "DB_NAME=mde2-msl-test" >> $GITHUB_ENV

    - name: Initialize database structure and lookup data
      run: php -r "require 'install.php'; createDatabaseStructure(\$connection); insertLookupData(\$connection);"

    - name: Start PHP built-in web server
      run: |
        # Start PHP server with error logging
        php -S localhost:8000 -t . tests/server.php 2>&1 > server.log &
        echo $! > server.pid
        sleep 10  # Wait for server to start
        
        # Test initial connection
        echo "Testing initial API endpoints:"
        curl -v http://localhost:8000/api/v2/general/alive
        echo "\nTesting licenses endpoint:"
        curl -v http://localhost:8000/api/v2/vocabs/licenses/all
        
        # Show initial logs
        echo "\nInitial server log contents:"
        cat server.log
        echo "\nPHP error log:"
        if [ -f /var/log/php_errors.log ]; then
          cat /var/log/php_errors.log
        fi

    - name: Set PHPUnit permissions
      run: chmod +x vendor/bin/phpunit

    - name: Run PHPUnit tests
      env:
        API_BASE_URL: http://localhost:8000
      run: |
        # Run tests
        vendor/bin/phpunit --configuration phpunit.xml --debug
        
        # Show final logs
        echo "\nFinal Server Log:"
        cat server.log

    - name: Stop PHP server
      if: always()
      run: kill $(cat server.pid)